apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    k8s-app: elasticsearch
    version: v7.10.2
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v7.10.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v7.10.2
    spec:
      # serviceAccountName: elasticsearch
      containers:
      - image: es-repo:tag
        name: elasticsearch
        imagePullPolicy: IfNotPresent
        # resources:
        #   # need more cpu upon initialization, therefore burstable class
        #   limits:
        #     cpu: 1000m
        #     memory: 3Gi
        #   requests:
        #     cpu: 100m
        #     memory: 3Gi
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 5
          timeoutSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: HOSTNAME_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node.name
          value: $(HOSTNAME_NAME).elasticsearch
        - name: cluster.name
          value: k8s-cluster
        - name: discovery.seed_hosts
          value: elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch
        - name: cluster.initial_master_nodes
          value: elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        # - name: "NAMESPACE"
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.namespace
        # - name: "MINIMUM_MASTER_NODES"
        #   value: "1"
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 32Gi
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      # initContainers:
      #   - image: alpine:3.6
      #     command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
      #     name: elasticsearch-init
      #     securityContext:
      #       privileged: true
