apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
spec:
  template:
    spec:
      containers:
      - name: chronograf
        envFrom:
          - secretRef:
              name: chronograf
