namespace: pantogram

bases:
- "../../base"

resources:
- "service.yaml"

images:
- name: repo
  newName: chronograf
  newTag: 1.8.8

patchesStrategicMerge:
- "deployment.yaml"

secretGenerator:
- name: chronograf
  envs:
  - .env
