apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        envFrom:
          - secretRef:
              name: mysql
        securityContext:
          runAsUser: 1000
