apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: app
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: datastore
