apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
spec:
  template:
    spec:
      containers:
      - name: datastore
        envFrom:
          - secretRef:
              name: datastore
