apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
spec:
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: datastore
        image: repository:tag
        ports:
          - containerPort: 8080
