apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-sh
data:
  run.sh: |
    #! /bin/sh

    until mysqladmin ping -h mysql --silent; do
      echo 'waiting for MySQL ...'
      sleep 2
    done

    echo "MySQL is now running!"
    exec /main
