apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeseries
spec:
  selector:
    matchLabels:
      app: timeseries
  template:
    metadata:
      labels:
        app: timeseries
    spec:
      containers:
      - name: timeseries
        image: repository:tag
        ports:
          - containerPort: 8081
        command:
          - /usr/local/bin/run.sh
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8081"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8081"]
          initialDelaySeconds: 15
        volumeMounts:
          - name: run-sh
            mountPath: /usr/local/bin
      volumes:
        - name: run-sh
          configMap:
            name: timeseries-sh
            defaultMode: 0755
