apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeseries
spec:
  selector:
    matchLabels:
      app: timeseries
  template:
    metadata:
      labels:
        app: timeseries
    spec:
      containers:
      - name: timeseries
        image: repository:tag
        ports:
          - containerPort: 8081
