namespace: pantogram

bases:
  - "../../base"

images:
  - name: repository
    newName: influxdb
    newTag: "1.8"

patchesStrategicMerge:
  - "deployment.yaml"

secretGenerator:
- name: influxdb
  envs:
  - .env
