apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeseries
spec:
  template:
    spec:
      containers:
      - name: app
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: timeseries
