namespace: pantogram

bases:
  - "../../base"

images:
  - name: envoy-repo
    newName: envoyproxy/envoy
    newTag: v1.18-latest
  - name: app-repo
    newName: 192.168.0.10:5000/timeseries
    newTag: v0.0.3

patchesStrategicMerge:
  - "deployment.yaml"

secretGenerator:
- name: timeseries
  envs:
  - .env
