apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
data:
  influxdb.yaml: |
    apiVersion: 1

    datasources:
    - name: influxdb
      type: influxdb
      access: proxy
      orgId: 1
      url: http://influxdb:8086
      user: pantogram
      password: pantogram
      database: pantogram
      isDefault: true
      editable: false
      version: 1
