apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    spec:
      containers:
      - name: grafana
        image: repository:tag
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources/influxdb.yaml
            name: influxdb
            subPath: influxdb.yaml
      volumes:
        - name: influxdb
          configMap:
            name: influxdb
